In [2]:
import numpy as np
import pandas as pd
import scipy.stats as ss
import itertools as it
from statsmodels.sandbox.stats.multicomp import multipletests
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.libqsturng import psturng
from pandas import DataFrame, Categorical, Series
import os

from utils.test_utils import *

In [3]:
f1 = pd.read_excel('data/demo_4gp.xlsx')
f1.head()

  group 4  Rapid Test    ELISA
0       A        2.99  175.081
1       A        3.14  134.622
2       A        0.72   30.159
3       A        2.50   63.562
4       A        1.75   49.606

In [4]:
new = []
new2 = []
for i in f1['group 4']:
    if i == 'A':
        new.append('HC')
        new2.append(1)
    if i == 'B':
        new.append('OPMD I')  
        new2.append(2)
    if i == 'C':
        new.append('OPMD II') 
        new2.append(3)
    if i == 'D':
        new.append('OSCC')  
        new2.append(4)
f1['分群'] = new2
f1['分群名'] = new
f1

    group 4  Rapid Test     ELISA  分群      分群名
0         A        2.99   175.081   1       HC
1         A        3.14   134.622   1       HC
2         A        0.72    30.159   1       HC
3         A        2.50    63.562   1       HC
4         A        1.75    49.606   1       HC
..      ...         ...       ...  ..      ...
603       C        3.31   170.291   3  OPMD II
604       D        1.56    21.879   4     OSCC
605       A        5.70   772.095   1       HC
606       D        8.34  1721.725   4     OSCC
607       C        5.37   240.912   3  OPMD II

[608 rows x 5 columns]

In [5]:
f2 = f1
Marker_Conc = 'ELISA'

In [6]:
Number_Name = dict(zip(f2['分群'],f2['分群名']))

writer = pd.ExcelWriter('./results/group4_stat-%s.xlsx'%Marker_Conc)

#case number
CaseNumber = []
for i in sorted(np.unique(f2['分群'])):
    CaseNumber.append(len(f2[f2['分群']==i][Marker_Conc]))

#Marker_Conc.(mean±sd)
MarkerConc = []
for i in sorted(np.unique(f2['分群'])):
    MarkerConc.append('%.3f±%.3f'%(np.mean(f2[f2['分群']==i][Marker_Conc]),np.std(f2[f2['分群']==i][Marker_Conc],ddof=1)))

#P-value
Groups_Conc = []
for i in sorted(np.unique(f2['分群'])):
    Groups_Conc.append(list(f2[f2['分群']==i][Marker_Conc]))

#分析
if len(Groups_Conc) == 2:
    res = ss.mannwhitneyu(Groups_Conc[0],Groups_Conc[1],alternative='two-sided')
elif len(Groups_Conc) == 3:
    res = ss.kruskal(Groups_Conc[0],Groups_Conc[1],Groups_Conc[2])
elif len(Groups_Conc) == 4:
    res = ss.kruskal(Groups_Conc[0],Groups_Conc[1],Groups_Conc[2],Groups_Conc[3])
elif len(Groups_Conc) == 5:
    res = ss.kruskal(Groups_Conc[0],Groups_Conc[1],Groups_Conc[2],Groups_Conc[3],Groups_Conc[4])
elif len(Groups_Conc) == 6:
    res = ss.kruskal(Groups_Conc[0],Groups_Conc[1],Groups_Conc[2],Groups_Conc[3],Groups_Conc[4],Groups_Conc[5])    
elif len(Groups_Conc) == 7:
    res = ss.kruskal(Groups_Conc[0],Groups_Conc[1],Groups_Conc[2],Groups_Conc[3],Groups_Conc[4],Groups_Conc[5],Groups_Conc[6]) 
elif len(Groups_Conc) == 8:
    res = ss.kruskal(Groups_Conc[0],Groups_Conc[1],Groups_Conc[2],Groups_Conc[3],Groups_Conc[4],Groups_Conc[5],Groups_Conc[6],Groups_Conc[7]) 
elif len(Groups_Conc) == 9:
    res = ss.kruskal(Groups_Conc[0],Groups_Conc[1],Groups_Conc[2],Groups_Conc[3],Groups_Conc[4],Groups_Conc[5],Groups_Conc[6],Groups_Conc[7],Groups_Conc[8])    
    

Pvalue = [res.pvalue] + ['']*(len(Groups_Conc)-1)


output_kruskal = pd.DataFrame(list(zip(CaseNumber,MarkerConc,Pvalue)))
output_kruskal.columns = ['Case Number','%s(mean±sd)'%Marker_Conc,'p-value']
output_kruskal.index = [Number_Name[i] for i in sorted(np.unique(f2['分群']))]
if len(Groups_Conc) == 2:
    output_kruskal.to_excel(writer,'MannwhiteneyU')
else:
    output_kruskal.to_excel(writer,'Kruskal')

In [7]:
pc = posthoc_dunn(a=f2, val_col=Marker_Conc, group_col='分群', p_adjust='bonferroni')[0]
Diff = posthoc_dunn(a=f2, val_col=Marker_Conc, group_col='分群', p_adjust='bonferroni')[1]
SE = posthoc_dunn(a=f2, val_col=Marker_Conc, group_col='分群', p_adjust='bonferroni')[2]
Z = posthoc_dunn(a=f2, val_col=Marker_Conc, group_col='分群', p_adjust='bonferroni')[3]
P = posthoc_dunn(a=f2, val_col=Marker_Conc, group_col='分群', p_adjust='bonferroni')[4]

bonferroni_mutiply = Cnk(len(np.unique(f2['分群'])),2)
adj_p = [i if i <1 else 1 for i in np.array(P)*bonferroni_mutiply]


idx = [Number_Name[i] for i in sorted(np.unique(f2['分群']))]
idx_vs_idx = []
for i in range(len(idx)):
    i2 = i
    if i != len(idx)-1:
        while True:
            i2 = i2+1
            idx_vs_idx.append('%s vs %s'%(idx[i], idx[i2]))
            if i2 == len(idx)-1:
                break
PostHoc_pd = pd.DataFrame(np.matrix([Diff,SE,Z,P,adj_p]).T)
PostHoc_pd.columns = ['檢定統計量','標準誤','Z(表準檢定統計量)','p(顯著性)','adj-p(調整後顯著性)']
PostHoc_pd.index = idx_vs_idx
PostHoc_pd.to_excel(writer,'Post-hoc')

pc.columns = idx
pc.index = idx
pc.to_excel(writer,'adj-p')
writer.save()